apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-golang
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-golang
    app.kubernetes.io/part-of: e2e-multiple-components
  name: component-golang
  namespace: appstudio-e2e-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-golang
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-golang
    spec:
      containers:
      - image: quay.io/codewindbtle/test-images:84fb60b521ae44e58c55a956eeafa52d
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
